var1 = int(input("Enter a digit between 0 and 9: "))

if var1 == 0:
  print("  * * *  ")
  print("*       *")
  print("*       *")
  print("*       *")
  print("         ")
  print("*       *")
  print("*       *")
  print("*       *")
  print("  * * *  ")
if var1 == 1:
  print("        *")
  print("        *")
  print("        *")
  print("         ")
  print("        *")
  print("        *")
  print("        *")
if var1 == 2:
  print("  * * *  ")
  print("       *")
  print("       *")
  print("       *")
  print("  * * *  ")
  print("*       ")
  print("*       ")
  print("*       ")
  print("  * * *  ")
if var1 == 3:
  print("  * * *  ")
  print("       *")
  print("       *")
  print("       *")
  print("  * * *  ")
  print("       *")
  print("       *")
  print("       *")
  print("  * * * ")
if var1 == 4:
  print("*      *")
  print("*      *")
  print("*      *")
  print("  * * *  ")
  print("       *")
  print("       *")
  print("       *")
if var1 == 5:
  print("  * * *  ")
  print("*       ")
  print("*       ")
  print("*       ")
  print("  * * *  ")
  print("        *")
  print("        *")
  print("        *")
  print("  * * *  ")
if var1 == 6:
  print("  * * *  ")
  print("*       ")
  print("*       ")
  print("*       ")
  print("  * * *  ")
  print("*       *")
  print("*       *")
  print("*       *")
  print("  * * *  ")
if var1 == 7:
  print("  * * *  ")
  print("        *")
  print("        *")
  print("        *")
  print("    ")
  print("        *")
  print("        *")
  print("        *")
  print("    ")
if var1 == 8:
  print("  * * *  ")
  print("*       *")
  print("*       *")
  print("*       *")
  print("  * * *  ")
  print("*       *")
  print("*       *")
  print("*       *")
  print("  * * *  ")
if var1 == 9:
  print("  * * *  ")
  print("*       *")
  print("*       *")
  print("*       *")
  print("  * * *  ")
  print("        *")
  print("        *")
  print("        *")
  print("  * * *  ")
